
; This file defines the Speedbreaker's behaviour.
; If you delete this file, SpeedFixer disables itself.
;
; The UNEDITED VALUES in this file match the game's vanilla (i.e. unmodified) values.
; SpeedFixer corrects invalid values; parameters you omit get their vanilla values.
;
; Each value in this file must be a decimal or whole number in [some range].




[Speedbreaker:Activation]
; Activation behaviour of the Speedbreaker.

; Constraints (unlimited duration if you don't define a value for it)
minCarSpeed = 48.0 ; [>=0] car speed required (in kph) to activate Speedbreaker
maxDuration = 10.0 ; [>=0] max. Speedbreaker duration (in seconds) per activation




[Speedbreaker:Recharging]
; Recharging behaviour of the Speedbreaker.

; Passive recharging (happens over time; disabled if you define neither parameter)
minCarSpeed  = 161.0 ; [>=0] car speed required (in kph) to trigger passive recharging
rechargeTime =  25.0 ; [>=0] how long (in seconds) fully passive recharging takes to complete

; Active recharging (triggered by drifting under the right conditions)
activeScale   =  0.5 ; [>=0]  how well active recharging scales with drifting performance
minDriftSpeed = 56.0 ; [>=0]  drifting speed required (in kph) to trigger active recharging
minDriftSlip  = 30.0 ; [0-90] slip angle required (in degrees) to trigger active recharging




[Speedbreaker:Physics]
; Physics-related effects of the Speedbreaker.

; Scale multipliers
timeScale    = 4.0 ; [>=1] dilation multiplier for in-game time
carMassScale = 2.0 ; [>=0] car-mass multiplier for collisions
gravityScale = 3.0 ; [any] gravity  multiplier for downforce

; Time-dilation transition
toDilationScale   = 1.0 ; [>=0] relative (to vanilla) transition speed to   dilation
fromDilationScale = 1.0 ; [>=0] relative (to vanilla) transition speed from dilation

; Steering (front wheels)
frictionBoost    = 75.0 ; [>=0]  boost (in percent) to steering friction
maxSteeringAngle = 60.0 ; [0-90] max. steering angle (in degrees)

; Drag forces
aeroDragReduction  =  75.0 ; [0-100]  reduction (in percent) of aerodynamic drag
steerDragReduction = 100.0 ; [15-100] reduction (in percent) of steering    drag